language: cpp
compiler: gcc
dist: trusty

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Qt5 SVG
  - sudo apt-get install libqt5svg5-dev
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  #- ./install_oclint
  # Download depencenies
  - ./download_other_githubs.sh

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Build Triangle
  - cd ../Triangle
  - qmake
  - make
  - cd ..
  - cd TriangleMeshCreator
  - ln -s ../Triangle/ToolTriangleConsole
  # Console
  - qmake -qt=qt5 ToolTriangleMeshCreatorConsole.pro
  - make debug
  - ./ToolTriangleMeshCreatorConsole --layer_height 1 --WKT "POLYGON((10 10,10 -10,-10 -10,-10 10))" --strategy 1 --n_layers 10 --fraction 0.9 --triangle_max_area 10.0 --triangle_min_angle 20.0 --profile
  # Desktop
  - qmake -qt=qt5 ToolTriangleMeshCreatorDesktop.pro
  - make debug
  - ./ToolTriangleMeshCreatorDesktop &
  - sleep 10
  - sudo killall ToolTriangleMeshCreatorDesktop
  # Get code coverage
  - ./get_code_cov
  - codecov
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  #- ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
